apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: media-processor-api
    newName: 443245368315.dkr.ecr.us-east-1.amazonaws.com/media-processor-api
    newTag: latest # GitHub Actions will automatically update this string on every push