apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base

images:
  - name: media-processor-api
    newName: 443245368315.dkr.ecr.us-east-1.amazonaws.com/media-processor-api
    newTag: 4457b201428380e497dd701c251aac4b36f9ea5e